### ISSUE TITLE
Vitamins return all zeros

### ISSUE THREAD

**Issue by davos-i** [CNM-University-of-Guelph-dev/NASEM-Model-Python#18]
Currently the `NASEM_out['vitamin_intakes']` exported from the call to `nd.NASEM_model` returns all 0's for each vitamin.
This is the df returned by https://github.com/CNM-University-of-Guelph/NASEM-Model-Python/blob/110dd9c9a2873aaee3b2c75a7da49b0814b52fa0/src/nasem_dairy/ration_balancer/execute_model.py#L136

**Comment by BFieguth** [comment]
Feeds that are not mineral/vitamin supplements have 0 for vitamin content in feed library. Rations without any supplements will result in 0 vitamin intake.
