### ISSUE TITLE
Dt_RUPIn Calculation

### ISSUE THREAD

**Issue by BFieguth** [CNM-University-of-Guelph-dev/NASEM-Model-Python#31]
Two options are available to calculate this Dt_RUPIn. Currently the model uses the sum() method but the second equation is reportedly more accurate.

**Comment by davos-i** [comment]
original comment in R. They calculate Dt_RUPIn.dt but it is never used but is reported. Commented out in code for now.
``` 
# The following diet level RUPIn is slightly more accurate than the feed level summation as the intercept exactly matches the regression equations, but feed level is very close.
    # if concerned about intercept, switch to using this eqn for RUP
```
