### ISSUE TITLE
calculate_TT_dcFdFA logical tests on Series will fail

### ISSUE THREAD

**Issue by davos-i** [CNM-University-of-Guelph-dev/NASEM-Model-Python#37]
When `An_StatePhys == 'Calf'`, the `calculate_TT_dcFdFA` function will fail because it tries to do logical tests on a pd.Series. But, it is expected that the tests be performed for each individual feed in the diet so that i can check `Fd_Category` for each row of diet_info.
See example of problem code here within the `calculate_TT_dcFdFA` function:
https://github.com/CNM-University-of-Guelph-dev/NASEM-Model-Python/blob/ceb891a9fbf8715d77ab277cd36c3d84e7cf9fa9/src/nasem_dairy/NASEM_equations/dev_nutrient_intakes.py#L597-L599

It is called in this function. I think it will actually need to all be re-written so that `calculate_*` functions expect single numeric values, not a whole pd.Series: https://github.com/CNM-University-of-Guelph-dev/NASEM-Model-Python/blob/ceb891a9fbf8715d77ab277cd36c3d84e7cf9fa9/src/nasem_dairy/NASEM_equations/dev_nutrient_intakes.py#L920

**Comment by BFieguth** [comment]
The issue is due to checking if Fd_Category != Calf Liquid Feed. Pushed up a fix with the refactor_Mlk_NP_g.
