### ISSUE TITLE
Dt_DMIn_Calf1 and Dt_DMIn_Lact2 Not Added to execute_model.py

### ISSUE THREAD

**Issue by BFieguth** [CNM-University-of-Guelph-dev/NASEM-Model-Python#63]
Functions to calculate Dt_DMIn_Calf1 and Dt_DMIn_Lact2 have been added but not implemented. Implementing would require a refactor of diet intakes. Should decide how predicted vs. user input DMI is being handled before refactoring.

**Comment by davos-i** [comment]
same as #36
